name: mkdocs-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar credenciais do Git
      - name: Configure Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 3. Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 4. Restaurar cache para pacotes Python
      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: mkdocs-material-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            mkdocs-material-${{ runner.os }}

      # 5. Instalar dependências
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs-material[imaging] mkdocs-mermaid2-plugin mkdocs-git-revision-date-localized-plugin mkdocs-swagger-ui-tag mkdocs-awesome-pages-plugin

      # 6. Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
